Make task 1 for Lab5, update CI

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -45,10 +45,12 @@ jobs:
         run: docker buildx ls
 
       - name: Log in to dockerhub
-        env:
-          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
+        run: |
+          if [[ -z "${{ vars.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
+            echo "Error: DOCKER_USERNAME or DOCKER_PASSWORD is missing."
+            exit 1
+          fi
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build Dockerfile image for amd64
         run: docker build --platform=linux/amd64 -t bohdanbezdrabko/httpserver:amd64 --push .
